// AUTO-GENERATED by scripts/gen-templates.ts — do not edit by hand.
// Run `bun run gen:templates` to regenerate. Guarded by a CI drift check.
import t0 from "./claude/statusline.sh" with { type: "text" };
import t1 from "./servant_root/.claude/commands/servant/delegate.md" with { type: "text" };
import t2 from "./servant_root/.claude/commands/servant/extract-memories.md" with { type: "text" };
import t3 from "./servant_root/.claude/commands/servant/fine-tune.md" with { type: "text" };
import t4 from "./servant_root/.claude/commands/servant/goal.md" with { type: "text" };
import t5 from "./servant_root/.claude/commands/servant/recall.md" with { type: "text" };
import t6 from "./servant_root/CLAUDE.md" with { type: "text" };

export interface ServantTemplate {
  /** Path relative to `src/templates/` (POSIX separators). */
  rel: string;
  /** File contents, embedded at build time. */
  content: string;
}

/** Every file under `src/templates/`, embedded so it ships inside the compiled binary. */
export const TEMPLATES: ServantTemplate[] = [
  { rel: "claude/statusline.sh", content: t0 },
  { rel: "servant_root/.claude/commands/servant/delegate.md", content: t1 },
  { rel: "servant_root/.claude/commands/servant/extract-memories.md", content: t2 },
  { rel: "servant_root/.claude/commands/servant/fine-tune.md", content: t3 },
  { rel: "servant_root/.claude/commands/servant/goal.md", content: t4 },
  { rel: "servant_root/.claude/commands/servant/recall.md", content: t5 },
  { rel: "servant_root/CLAUDE.md", content: t6 },
];
