// Config files the mattpocock engineering skills read as prose (to-tickets, to-spec, triage,
// wayfinder). Normally written by `/setup-matt-pocock-skills` per repo; servant pre-writes them
// per workspace instead, because a workspace root isn't a git clone (so the skills can't
// auto-detect a tracker) and because the tracker is servant's own local board rather than any
// repo's GitHub Issues.
//
// These documents are **load-bearing**: all of the `/wayfinder` operations live here rather than in
// code, so prose is part of the migration surface (ADR-0011). They used to be written once and never
// refreshed, which meant an existing workspace would keep instructing agents to run `gh issue
// create` forever. They now carry a content stamp, and `writeStamped` rewrites them when it moves.

import { createHash } from "node:crypto";

export const AGENT_SKILLS_MARKER = "<!-- servant:agent-skills -->";

/** Marks a servant-generated agent doc, and carries the hash of the content it was generated from. */
const STAMP_PREFIX = "<!-- servant:agent-doc v=";

/** 12 hex chars of sha256 — the same shape as the insights setup fingerprint. */
function contentStamp(body: string): string {
  return createHash("sha256").update(body).digest("hex").slice(0, 12);
}

/**
 * A generated doc with its content stamp on the first line.
 *
 * The stamp is derived from the content rather than hand-bumped, so there is no version constant to
 * forget: change the prose and every workspace picks it up on its next spawn. It is also what makes
 * the version legible in the file itself, so two workspaces can be compared at a glance.
 */
export function stampDoc(body: string): string {
  return `${STAMP_PREFIX}${contentStamp(body)} — generated by servant; edits here are overwritten -->\n${body}`;
}

/** The board conventions doc (docs/agents/issue-tracker.md). */
export function renderIssueTrackerDoc(workspace: string): string {
  return stampDoc(`# Issue tracker: the servant board

Tickets and specs for this workspace live on **servant's own board** — a local SQLite database at
the servant root, read and written by \`servant\` commands. There is no GitHub, no \`gh\`, no account
and no network: every operation below works offline, and works whether or not the board viewer is
open.

Each workspace is a board of its own, so ticket numbers are small and board-scoped. This workspace's
board is \`${workspace}\`. Every command below defaults to the current workspace — pass
\`--ws ${workspace}\` explicitly when you are not running from inside it.

## Conventions

- **Create a ticket**: \`servant ticket new --title "..." --body "..." --labels "spec"\`
  (heredoc for multi-line bodies). It prints the new number; add \`--json\` to read it back
  programmatically. Labels are freeform strings — nothing needs creating first.
- **Read a ticket**: \`servant ticket show <number>\` — body, labels, claim, both directions of its
  blocking edges, and its comments.
- **List this workspace's tickets**: \`servant tasks --ws ${workspace}\` (add \`--state all\` for
  closed ones too). \`servant tasks --frontier --ws ${workspace} --json\` reports what is
  dispatchable.
- **Comment**: \`servant ticket comment <number> --body "..."\`.
- **Apply / remove labels**: \`servant ticket label <number> --add "a,b" --remove "c"\`.
- **Move between states**: \`servant ticket status <number> <todo|in_progress|in_review|done>\`.
- **Close**: \`servant ticket close <number> --comment "..."\`.

\`blocked\` and \`ready\` are **not** states you set — both are derived from open dependencies, so
they can never disagree with what \`servant tasks --frontier\` reports.

## Blocking

One representation, and it is a real graph:

- **Record a blocker**: \`servant ticket block <number> --on <blocker>\`. Add
  \`--on-ws <workspace>\` when the blocker is on another workspace's board — cross-board
  dependencies are expressible, and stored against a global id so renumbering cannot break them.
- **Drop one**: \`servant ticket unblock <number> --on <blocker>\`.
- A dependency that would create a cycle is **rejected when you add it**. Do not write blocking
  into the body as prose — a \`Blocked by:\` line in a ticket body is read by nothing.
- \`servant ticket show\` reports both directions: what blocks this, and what this blocks.

## Claims

Which session is carrying a ticket:

- **Take it**: \`servant claim <number> --session <workspace>-t<number>\`. Idempotent — re-claiming
  a ticket you already hold is not an error.
- **Release it**: \`servant claim <number> --release --session <name>\`, as soon as the work is
  done or abandoned, so the ticket returns to the frontier.
- **History**: \`servant claim <number> --history\`.

Claiming someone else's ticket is an explicit, recorded transfer. Never work a ticket you have not
claimed.

## When a skill says "publish to the issue tracker"

\`servant ticket new\` on this workspace's board, labeled \`spec\` for a spec and \`ticket\` for a
tracer-bullet ticket, plus any triage label.

## When a skill says "fetch the relevant ticket"

Run \`servant ticket show <number>\`.

## Wayfinding operations (used by /wayfinder)

A **map** is one ticket with **child** tickets hanging off it, all on this board.

- **Map**: \`servant ticket new --labels "wayfinder:map" --title "..." --body "..."\` holding the
  Destination / Out-of-scope / Decisions-so-far / Not-yet-specified body.
- **Child ticket**: \`servant ticket new --parent <map> --labels "wayfinder:<type>"\` where
  \`<type>\` is \`research\`, \`prototype\`, \`grilling\` or \`task\`. The parent link is structural,
  not a line in the body.
- **Blocking between children**: \`servant ticket block <child> --on <other-child>\`.
- **Frontier query**: \`servant tasks --frontier --ws ${workspace} --json\` — the \`ready\` bucket
  is exactly the unblocked, unclaimed set. Do not re-derive it by reading bodies.
- **Claim**: \`servant claim <n> --session <name>\` (see Claims above).
- **Resolve**: \`servant ticket comment <n> --body "<answer>"\`, then
  \`servant ticket close <n>\`, then append a pointer to the map's Decisions-so-far.

Edit map prose one section at a time rather than rewriting the whole body, so two sessions working
the same map cannot silently overwrite each other.
`);
}

/** Domain-doc consumer rules (docs/agents/domain.md) — servant adopts CONTEXT.md + docs/adr/. */
export function renderDomainDoc(): string {
  return stampDoc(`# Domain Docs

How the engineering skills should consume this workspace's domain documentation when exploring.

## Before exploring, read these

- **\`CONTEXT.md\`** at the workspace root — the shared language / domain glossary.
- **\`docs/adr/\`** — read ADRs that touch the area you're about to work in.

If any of these don't exist yet, **proceed silently**. The \`/domain-modeling\` skill (reached via
\`/grill-with-docs\` and \`/improve-codebase-architecture\`) creates them lazily when terms or
decisions actually get resolved.

## File structure

\`\`\`
<workspace>/
├── CONTEXT.md
├── docs/adr/
│   ├── 0001-<slug>.md
│   └── 0002-<slug>.md
└── repos/            ← mounted repo worktrees
\`\`\`

## Use the glossary's vocabulary

When your output names a domain concept (a ticket title, a refactor proposal, a hypothesis, a test
name), use the term as defined in \`CONTEXT.md\`. If the concept isn't in the glossary yet, that's a
signal — either you're inventing language the project doesn't use (reconsider) or there's a real
gap (note it for \`/domain-modeling\`).

## Flag ADR conflicts

If your output contradicts an existing ADR, surface it explicitly:

> _Contradicts ADR-0007 (event-sourced orders) — but worth reopening because…_
`);
}

/** Triage label mapping (docs/agents/triage-labels.md) — the five canonical defaults. */
export function renderTriageLabelsDoc(): string {
  return stampDoc(`# Triage Labels

The skills speak in terms of five canonical triage roles. This table maps those roles to the label
strings used on the servant board. The label strings equal their canonical names (defaults).

| Label in mattpocock/skills | Label on the board | Meaning                                  |
| -------------------------- | ------------------ | ---------------------------------------- |
| \`needs-triage\`             | \`needs-triage\`     | Needs evaluation                         |
| \`needs-info\`               | \`needs-info\`       | Waiting on more information              |
| \`ready-for-agent\`          | \`ready-for-agent\`  | Fully specified, ready for an AFK agent  |
| \`ready-for-human\`          | \`ready-for-human\`  | Requires human implementation            |
| \`wontfix\`                  | \`wontfix\`          | Will not be actioned                     |

When a skill mentions a role (e.g. "apply the AFK-ready triage label"), use the corresponding label
string from this table. Labels are freeform on the board — apply one with
\`servant ticket label <n> --add "<label>"\`; nothing needs creating first.
`);
}

/**
 * The `## Agent skills` block injected into the workspace CLAUDE.md so the skills know where their
 * config lives. Wrapped in AGENT_SKILLS_MARKER for idempotent re-generation.
 */
export function renderAgentSkillsBlock(workspace: string): string {
  return `${AGENT_SKILLS_MARKER}
## Agent skills

The mattpocock engineering skills are installed (plugin \`mattpocock-skills\`). Their per-workspace
config lives under \`docs/agents/\` — read the relevant file when a skill needs it.

### Issue tracker

Tickets live on **servant's own board** — a local SQLite database, no GitHub and no network. This
workspace is its own board, so ticket numbers are small. File with \`servant ticket new\`, read with
\`servant ticket show <n>\`, list with \`servant tasks --ws ${workspace}\`. See
\`docs/agents/issue-tracker.md\` for every operation, including the \`/wayfinder\` ones.

### Triage labels

The five canonical triage labels (defaults). See \`docs/agents/triage-labels.md\`.

### Domain docs

Single-context: \`CONTEXT.md\` + \`docs/adr/\`. See \`docs/agents/domain.md\`.
`;
}
