#!/usr/bin/env bun
// Generate `src/version.generated.ts` with the build-time version, derived from
// `git describe --tags --always` (falling back to package.json `version`). Run on `prebuild`
// so the compiled binary embeds a stable version even though no `.git` ships with it.
import { dirname, join, relative } from "node:path";
import pkg from "../package.json" with { type: "json" };

const here = dirname(Bun.fileURLToPath(import.meta.url));
const repoRoot = join(here, "..");
const outFile = join(repoRoot, "src", "version.generated.ts");

function gitDescribe(): string | null {
  try {
    const proc = Bun.spawnSync(["git", "describe", "--tags", "--always"], {
      cwd: repoRoot,
      stdout: "pipe",
      stderr: "ignore",
    });
    if (proc.exitCode !== 0) return null;
    const out = proc.stdout.toString().trim();
    return out.length > 0 ? out : null;
  } catch {
    return null;
  }
}

const version = gitDescribe() ?? pkg.version;

const body = `// AUTO-GENERATED by scripts/gen-version.ts — regenerated on \`prebuild\` from \`git describe\`.
// The committed value is a placeholder; the real version is stamped into the compiled binary
// at build time. In dev (\`bun run\`) the live \`git describe\` is used instead (see version.ts).
export const BUILD_VERSION = ${JSON.stringify(version)};
`;

await Bun.write(outFile, body);
console.log(`gen:version — ${version} → ${relative(repoRoot, outFile)}`);
