#!/usr/bin/env bun
// Generate `src/templates/index.generated.ts`: a single embedded manifest of every file
// under `src/templates/`. Each file is imported with `with { type: "text" }`, which Bun
// inlines identically under `bun run` and `bun build --compile` — so the CLI reads its
// templates the same way in dev and in the standalone binary (no `import.meta.url` FS reads).
//
// Run `bun run gen:templates`. The output is committed and guarded by a CI drift check
// (`bun run gen:templates && git diff --exit-code`), and regenerated on `prebuild`.
import { readdir } from "node:fs/promises";
import { dirname, join, posix, relative, sep } from "node:path";

const here = dirname(Bun.fileURLToPath(import.meta.url));
const repoRoot = join(here, "..");
const templatesDir = join(repoRoot, "src", "templates");
const outFile = join(templatesDir, "index.generated.ts");
const OUT_BASENAME = "index.generated.ts";

async function listFiles(root: string): Promise<string[]> {
  const out: string[] = [];
  async function walk(dir: string): Promise<void> {
    const entries = await readdir(dir, { withFileTypes: true });
    for (const entry of entries) {
      const full = join(dir, entry.name);
      if (entry.isDirectory()) await walk(full);
      else if (entry.isFile()) out.push(full);
    }
  }
  await walk(root);
  return out;
}

function toPosix(rel: string): string {
  return sep === "/" ? rel : rel.split(sep).join(posix.sep);
}

const files = (await listFiles(templatesDir))
  .map((abs) => toPosix(relative(templatesDir, abs)))
  .filter((rel) => rel !== OUT_BASENAME)
  .sort();

const importLines = files.map((rel, i) => `import t${i} from "./${rel}" with { type: "text" };`);
const entryLines = files.map((rel, i) => `  { rel: ${JSON.stringify(rel)}, content: t${i} },`);

const body = `// AUTO-GENERATED by scripts/gen-templates.ts — do not edit by hand.
// Run \`bun run gen:templates\` to regenerate. Guarded by a CI drift check.
${importLines.join("\n")}

export interface ServantTemplate {
  /** Path relative to \`src/templates/\` (POSIX separators). */
  rel: string;
  /** File contents, embedded at build time. */
  content: string;
}

/** Every file under \`src/templates/\`, embedded so it ships inside the compiled binary. */
export const TEMPLATES: ServantTemplate[] = [
${entryLines.join("\n")}
];
`;

await Bun.write(outFile, body);

// Format the output so it always matches `bun run format:check` (the committed file and the
// CI-regenerated file must be byte-identical, or the drift check fails on formatting alone).
const fmt = Bun.spawn(["bunx", "biome", "format", "--write", outFile], {
  cwd: repoRoot,
  stdout: "ignore",
  stderr: "inherit",
});
const code = await fmt.exited;
if (code !== 0) {
  throw new Error(`biome format failed on ${outFile} (exit ${code})`);
}

console.log(`gen:templates — wrote ${files.length} templates to ${relative(repoRoot, outFile)}`);
