#!/usr/bin/env bun
// Render the Homebrew formula `Formula/servant.rb` for a published release. Reads the per-arch
// sha256 sums from the release artifacts and prints the formula to stdout.
//
//   bun run scripts/gen-formula.ts <tag> <artifacts-dir>
//
// <tag> is the git tag (e.g. `v0.2.0`); <artifacts-dir> contains the uploaded
// `servant-<platform>.tar.gz.sha256` files. Used by release.yml to bump the tap repo
// `Bakar0/homebrew-tap`, and runnable locally to preview the formula.
import { join } from "node:path";

const REPO = "Bakar0/ai-servant-cli";
const ASSETS = {
  darwinArm64: "servant-darwin-arm64",
  darwinX64: "servant-darwin-x64",
  linuxX64: "servant-linux-x64",
} as const;

const [tag, artifactsDir] = process.argv.slice(2);
if (!tag || !artifactsDir) {
  console.error("usage: bun run scripts/gen-formula.ts <tag> <artifacts-dir>");
  process.exit(1);
}

const version = tag.replace(/^v/, "");

async function sha256For(asset: string, dir: string): Promise<string> {
  // Artifacts may be nested one directory deep (actions/download-artifact groups by name).
  const candidates = [
    join(dir, `${asset}.tar.gz.sha256`),
    join(dir, asset, `${asset}.tar.gz.sha256`),
  ];
  for (const path of candidates) {
    const file = Bun.file(path);
    if (await file.exists()) {
      const first = (await file.text()).trim().split(/\s+/)[0];
      if (first) return first;
    }
  }
  throw new Error(`sha256 file not found for ${asset} under ${dir}`);
}

function url(asset: string): string {
  return `https://github.com/${REPO}/releases/download/${tag}/${asset}.tar.gz`;
}

const [shaDarwinArm64, shaDarwinX64, shaLinuxX64] = await Promise.all([
  sha256For(ASSETS.darwinArm64, artifactsDir),
  sha256For(ASSETS.darwinX64, artifactsDir),
  sha256For(ASSETS.linuxX64, artifactsDir),
]);

const formula = `# AUTO-GENERATED by scripts/gen-formula.ts on each release — do not edit by hand.
class Servant < Formula
  desc "AI servant CLI — enhances developer and coding-agent workflows"
  homepage "https://github.com/${REPO}"
  version "${version}"
  license "MIT"

  on_macos do
    on_arm do
      url "${url(ASSETS.darwinArm64)}"
      sha256 "${shaDarwinArm64}"
    end
    on_intel do
      url "${url(ASSETS.darwinX64)}"
      sha256 "${shaDarwinX64}"
    end
  end

  on_linux do
    on_intel do
      url "${url(ASSETS.linuxX64)}"
      sha256 "${shaLinuxX64}"
    end
  end

  def install
    bin.install "servant"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/servant --version")
  end
end
`;

process.stdout.write(formula);
