// AUTO-GENERATED by scripts/gen-version.ts — regenerated on `prebuild` from `git describe`.
// The committed value is a placeholder; the real version is stamped into the compiled binary
// at build time. In dev (`bun run`) the live `git describe` is used instead (see version.ts).
export const BUILD_VERSION = "0.0.1";
